REM INPUT COMMAND DEMONSTRATION
REM INPUT COMMAND WAITS FOR PROGRAM TO INPUT VALUE
CLS
INPUT N
PRINT N



REM INPUT COMMAND WITH MESSAGE
INPUT "Enter your Age"; N
PRINT N


REM INPUT COMMAND WITH MESSAGE with semicolon
INPUT "Enter your Age", N
PRINT N

