REM INTRODUCTION TO EXPRESSION

REM SIMPLE ARITHMATIC EXPRESSION
PRINT 3+5

REM SINGLE NUMBER IS ALSO EXPRESSION
PRINT 3

REM MULTIPLE SMALL EXPRESSIONS MAKES BIGGER EXPRESSION
PRINT 3+5*(9+6)


REM BELOW ARE SIMPLE STRING EXPRESSIONS
REM STRING EXPRESSION STARTS AND ENDS WITH DOUBLE QUOTES

PRINT "HELLO"
PRINT "ABCD"
PRINT "@#$@#$@#$@"

REM LIMITED ARITHMATIC LIKE OPERATIONS ON STRINGS - concatenate
PRINT "HELLO" + " " + "WORLD"

