REM DEMONSTRATION OF VARIABLES


REM ASSIGNING VALUE OF 3 TO VARIABLE X
X = 3
PRINT X

REM ASSIGNING VALUE OF 10  TO VARIABLE X
X=10
PRINT X

REM VALUES OF VARIABLES AND ASSIGNING TO 3RD VARIABLE Z
Y=15
Z = X+Y

PRINT "X=";X;"Y=";Y;"Z=";Z

REM MORE COMPLEX EXPRESSION WITH VARIABLES. THIS IS (X+Y) SQUARE
M = X ^ 2 + 2 * X*Y + Y^2

PRINT "X+Y WHOLE SQUARE IS"; M

REM INCREMENTING VARIABLE VALUE BY ONE
REM FIRST PRINT COMMAND WILL PRINT 10 AND THEN IT WILL PRINT 11
C = 10
PRINT C

C = C+1
PRINT C

REM DEFAULT VALUE OF VARIABLE IS 0-BELOW 0 IS PRINTED AS VARIABLE OF D WAS UNINITIALIZED
PRINT D

REM BELOW ARE SOME VALID VARIABLE NAMES

TEMPRETURE = 35
AVG = 44
COUNTER=1
MAX=100000000
MIN=-1


